version: '3'

services:
    web:
        image: node:lts-alpine3.17
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - '8080:8080'
        environment:
            NODE_ENV: development
        command: npm run dev
